### PR TITLE
Conan package

### PR DESCRIPTION
**Pull request by mropert**
Add conan package.

If you prefer out of source packaging, use the commented `source` part and put the file in another repo...

### CODE REVIEW

**Comment by OvermindDL1** [comment]
Python?  In a C++ project?  Why not just use pure CMake dependency management so projects that want to use NamedType just have to add a line or two to their cmake file since this project already uses cmake?

**Comment by conradjones** [comment]
There is no CMake in this project ? Maybe it was removed since your comment.

Conan has established it's self a reasonable package manager for C++, many people are using it and including a conanfile.py in a project is a sensible move these days, if you're not using conan the conanfile.py has no impact on you except the 1-2kb of diskspace that it uses.

**Comment by travnick** [comment]
see #37. In https://github.com/AMS21/NamedType/network there is a CMake

**Comment by peter-moran** [comment]
I am also interested in consuming this library via conan.

**Comment by jputcu** [comment]
This pull request can be closed, it is available in conan: https://github.com/conan-io/conan-center-index/tree/master/recipes/namedtype

**Pull request closed without merging**
